name: Run Test Script

on:
  schedule:
    # Thursday 21:25 UTC
    - cron: "40 18 * * 4"
    # Sunday 19:55 UTC
    - cron: "20 17 * * 0"
    # Monday 08:55 UTC
    - cron: "20 06 * * 1"
  workflow_dispatch:   # manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run script
        env:
          TZ: Europe/Berlin
          ZHS_USER: ${{ secrets.ZHS_USER }}
          ZHS_PASS: ${{ secrets.ZHS_PASS }}
          CHOICE: 0,1,4
          STREET: ${{ secrets.STREET }}
          Thrs_time: 21:30
          Fri_time: 20:00
          Sat_time: 09:00
          STREET_NUMBER: ${{ secrets.STREET_NUMBER }}
          POSTAL_CODE: ${{ secrets.POSTAL_CODE }}
          CITY: Munich
          BIRTHDATE: ${{ secrets.BIRTHDATE }}

        run: python test.py